version: '3'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: lukaswire/polls
    env_file: .env
    container_name: poll-bot
    ports:
      - 8080:8080
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres:12.2
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - poll-bot-db:/var/lib/postgresql/data/

volumes:
  poll-bot-db:
