version: '3'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: lukaswire/polls
    env_file: .env
    container_name: poll-bot
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres:12.2
    environment:
      - POSTGRES_USER=unicorn_user
      - POSTGRES_PASSWORD=magical_password
      - POSTGRES_DB=rainbow_database
    en:
      - database.env # configure postgres
    volumes:
      - poll-bot-db:/var/lib/postgresql/data/

volumes:
  poll-bot-db: # named volumes can be managed easier using docker-compose
