name: Docker image build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.3

      - name: Execute test with gradle
        run: ./gradlew test

      - uses: actions/checkout@master
      - name: Build docker image
        uses: docker/build-push-action@v1
        with:
          repository: lukaswire/polls
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_with_ref: true
          push: false
